### ISSUE TITLE
Add docs for building for Android (e.g. using Android Studio)

### ISSUE THREAD

**Issue by appgurueu** [minetest/dev.luanti.org#110]
The process is quite straightforward, but a step-by-step guide would be nice nevertheless.

I see that @MisterE123 has already published such a guide [on the forums](https://forum.luanti.org/viewtopic.php?t=28869) (though the license is unclear, and it can be simplified now that irrlichtmt is no longer separate). I imagine @rollerozxa might also have some helpful input.

**Comment by wsor4035** [comment]
the forum post contents have been licensed CCC0 by MisterE on the discord/irc/matrix channel

**Comment by rollerozxa** [comment]
In addition to building with Android Studio, what may be more useful is a guide for building with simply Gradle and the command-line tools. It has a bit more steps for setting up your SDK folder but ends up being a lot lighter when you just want to build it for Android and don't need the fancy IDE that Android Studio gives you.

I wrote this: https://principia-web.se/wiki/Compiling_Principia#android for building Principia for Android with the command-line tools, instructions which also applies to Luanti when switching out the source repository and build folder. The Principia Wiki is CC-BY 4.0 licensed, okay if anyone wants to adopt it for Luanti.

**Comment by mark-wiemer** [comment]
Would someone mind linking the exact license post from the IRC archive for posterity?

**Comment by mark-wiemer** [comment]
Also, for non-Luanti-specific guides, like "how to use Gradle", I'll continue to highly recommend linking to other docs for now. While we can write our own, I think the best way to spend our time is on Luanti-specific stuff, esp in these early days, and we can revisit simple, on-site guides for basic tooling later. Just my two cents.

**Comment by rollerozxa** [comment]
This is not how to use Gradle, this is how to compile Luanti for Android.

**Comment by mark-wiemer** [comment]
Gotcha, thanks for clarifying, I misread the original message

**Comment by appgurueu** [comment]
I plan to document both: How to build with CLI tools and how to build using Android Studio. The latter might also be a bit more platform-independent, and there already is a decent guide by MisterE we can port. I've tested both locally.

I will link to [gradle (wrapper)](https://docs.gradle.org/current/userguide/gradle_wrapper.html) and [adb](https://developer.android.com/tools/adb) docs, but to get developers who just want to build up to speed I will also include the couple short commands they need to run.
