### ISSUE TITLE
[discussion]: wiki and dev wiki merging

### ISSUE THREAD

**Issue by wsor4035** [minetest/dev.luanti.org#12]
my current proposal is for the long talked about merging of wikis (see dev irc discussions, zughy forum post, etc)

points
* convert to markdown what is useful in wiki.minetest.net
* pr it here
* merge it
* redirect wiki.minetest.net to dev.luanti.org

**Comment by rollerozxa** [comment]
Been a long time coming.

As for what to do with the MTG content on the regular wiki, it can be moved somewhere separate (like in the github wiki for the minetest/minetest_game repo), but I personally don't really care for much of anything of it and it might as well be thrown away with a final MediaWiki export made for it for archival purposes if nobody takes up the mantle of caring for it.

**Comment by rollerozxa** [comment]
Also if we were to merge the two wikis and import over more player related pages, then I feel like this should be pointed to wiki.luanti.org rather than dev.luanti.org, maybe even dropping the "Developer" in the name. The focus would still be on the engine itself and not any particular game, making it mostly for dev and modding purposes.

**Comment by GreenXenith** [comment]
I support dropping "Developer", but I also would suggest converting to "documentation" as a whole (wiki, dev, docs, and api could all redirect here). It's Luanti Documentation, whether it's gamedev, content installation, or server setup.

**Comment by wsor4035** [comment]
cc @appgurueu for what to do with mtg stuff.
be it burn (preferably), convert and put in mtg repo, etc

**Comment by appgurueu** [comment]
That's a question for @minetest/game more generally (specifically @sfan5, @SmallJoker).

Good game docs / guides can live on in the MTG repo I think. If the wiki is to be taken offline (why?) then archive & dump would be the least IMO.

**Comment by wsor4035** [comment]
> If the wiki is to be taken offline (why?)

not sure where you got this idea from. the idea is to merge, and point the two old urls to one new one

---------------

as for worthless mtg examples, stuff like https://wiki.luanti.org/Obsidian has basically no value at all given craft guides exist, and may very well be wrong if anything has been changed in the many years since that has been created

**Comment by wsor4035** [comment]
see https://github.com/minetest/dev.luanti.org/issues/15
