### ISSUE TITLE
Importing content from the Voxelmanip Wiki

### ISSUE THREAD

**Issue by rollerozxa** [minetest/dev.luanti.org#32]
I made the Voxelmanip Wiki last year to collect various modding and development-related documentation in one place, after the demise of minetest_docs and the Developer Wiki not being very usable at the time. Now that we've got this new wiki, importing everything is a good idea - I was hoping this would happen one day anyways.

This issue is mostly for me personally to keep track of what I have left to import, and at the end I'll make the imported pages from the Voxelmanip Wiki simply redirect to here.

- [x] Compiling on Windows using MSYS2
- [x] ~~Custom Fonts~~
- [x] Custom Lua Mapgen
- [x] Development Tools
- [X] ~~Distributing Minetest Games~~ (This page has become quite outdated. I'll get to it some other time.)
- [x] Documentation Resources
- [X] Filesystem
- [x] ~~Game Namespaces~~ (ContentDB should preferably be able to store this)
- [x] Game Theme Reimplementation
- [X] Improving Build Times
- [X] ItemStackMetaData
- [X] Keeping World Compatibility
- [x] Limitations
- [X] LuaJIT
- [X] LuaJIT Differences
- [X] Lua Environment
- [X] ~~Main Page~~
- [X] Mapgen Optimisations
- [x] Meshes
- [X] MetaData
- [X] ~~Minetest NMPR~~
- [x] ModStorage
- [x] ~~Mod Dependency Management~~
- [X] ~~Mod Soup~~
- [X] Modchannels
- [X] NodeMetaData
- [x] Nodes
- [X] Object Properties
- [X] Persistence
- [X] PlayerMetaData
- [X] Random
- [X] Raycast
- [X] Remote Media
- [ ] Right to a Name
- [x] Schematics
- [X] Setting up a server
- [X] Spawn Algorithm
- [X] Texture Modifiers
- [x] Textures
- [X] Timing and Event loop
- [x] Using Blockbench
- [X] Vector API
- [X] VoxelArea
- [X] ~~env meta.txt~~
- [X] ~~minetest docs~~

**Comment by mark-wiemer** [comment]
Nice work :)
