### ISSUE TITLE
Finalize naming conventions

### ISSUE THREAD

**Issue by mark-wiemer** [minetest/dev.luanti.org#42]
Ensure article files are all at least named with the same convention. Google recommends kebab-case for URLs, and I'd recommend the same for filenames for consistency

**Comment by rollerozxa** [comment]
I standardised all the filenames to be lowercase and use kebab-case in https://github.com/minetest/dev.luanti.org/commit/00b9155be281139fd29262a562446dabcc16bade, and the URLs followed. Redirect aliases should be set up for everything so there won't be 404's.
