### ISSUE TITLE
[Discussion] Content format: Markdown, AsciiDoc, both, other?

### ISSUE THREAD

**Issue by mark-wiemer** [minetest/dev.luanti.org#59]
https://gohugo.io/content-management/formats/

Hugo supports many formats, along with mixing formats. We should update this repo's guidelines to mention our preferred formats and why so that new contributors can author content with confidence.

**Comment by rollerozxa** [comment]
Always using Markdown for page formats should be preferred I think. Maybe this should be written in https://dev.luanti.org/about-this-site/ or on a new style guidelines page.

**Comment by appgurueu** [comment]
The admonitions are a shame, but for almost everything else I still prefer Markdown and standardization on one format trumps the alternative.

**Comment by mark-wiemer** [comment]
I'm also in favor of just Markdown, for style guidelines see #60

**Comment by mark-wiemer** [comment]
Going to close this as completed, seems we have lazy consensus on Markdown-only.
