### ISSUE TITLE
[Discussion] In-page editor

### ISSUE THREAD

**Issue by mark-wiemer** [minetest/dev.luanti.org#69]
Maybe trusted users will have access to in-page editing like a traditional wiki, with some pages being protected similar to Wikipedia?

Pros:
- Much smoother contribution experience

Cons:
- High cost of development as our current framework is not very well-built for this
- Still need to support traditional contribution flow of GH PRs for untrusted users

Ref #65

**Comment by mark-wiemer** [comment]
Personally I'm very OK with the status quo, I think we have a contributions guidelines page somewhere and we can improve that to enhance the GH PR flow. No, GH isn't libre software, but I personally don't have an issue with that as the default, esp. as it is the Luanti default for all other repos as discussed in #65. Disclaimer: I do work for Microsoft which owns GitHub, but all opinions are my own on this acct

**Comment by mark-wiemer** [comment]
From wsor on #minetest-docs IRC: just going to drop the only cms like thing ive seen for github pages [pages-cms/pages-cms](https://github.com/pages-cms/pages-cms)

**Comment by mark-wiemer** [comment]
Pages CMS, which could plug in to Hugo, looks decent but apparently is built primarily for trusted contributors to quickly publish changes without review. I created https://github.com/pages-cms/pages-cms/discussions/136 for further discussion with them.

**Comment by appgurueu** [comment]
In my opinion not worth looking into extensively at the moment. If there is a contributor who would like this feature strongly, they can add it themselves.

**Comment by Wuzzy2** [comment]
I don't understand this issue. I never suggested to develop this feature from scratch. it would be perfectly reasonable to just install a ready-to-go wiki software (other than MediaWiki). Or is wiki software as a whole (even lightweight ones) completely off the table.

**Comment by mark-wiemer** [comment]
Even lightweight wiki softwares are much more complex than static site generators. Generally I am against moving to a wiki software unless there's a good reason, hence the discussion in the other issue. I'm curious, are there are any upsides to wiki softwares aside from in-page editing?

**Comment by wsor4035** [comment]
this can be handled in the future if necessary, but i see no point to keep this open currently. the content is in markdown and is easy exportable/movable to another thing if needed.
