### ISSUE TITLE
Require code blocks to have a language

### ISSUE THREAD

**Issue by mark-wiemer** [minetest/dev.luanti.org#85]
Fenced code blocks can easily use a language identifier to inform transpilers how to apply syntax highlighting :)

![image](https://github.com/user-attachments/assets/41ecf121-daab-4527-951e-d092a5b78a02)

Before:

![image](https://github.com/user-attachments/assets/31e94cf7-37fa-4370-8cb2-f092e98bbc7e)

After:

![image](https://github.com/user-attachments/assets/ea30dfd8-0dde-47e5-b590-ad8506380fef)

- CI fails with useful error message if any fenced code block (marked with \`\`\`, triple backticks) does not declare a language (valid langs include `txt`)
- Language identifier does not have to be valid for this issue, just some alphanumeric text immediately after the triple backticks is sufficient. Bonus points if we do have lang identifier enforcement, but err msgs should include the entire valid list if so!
- Other code block syntaxes, like HTML, are out of scope for this issue, current focus is Markdown.

**Comment by mark-wiemer** [comment]
wsor on IRC:

> went down a rabbit hole on <https://github.com/minetest/dev.luanti.org/issues/85>
there is <https://github.com/CICDToolbox/markdown-lint> ci action,
which uses <https://github.com/igorshubovych/markdownlint-cli>
which uses <https://github.com/DavidAnson/markdownlint> (seems to be popular at the core of a lot of things)
but it doesnt have an option for what mark wants. it has an option for extensions <https://www.npmjs.com/search?q=keywords:markdownlint-rule> of which none match what mark wants
so unless someone wants to write an extension for this, i kinda am leaning towards just closing the issue

**Comment by mark-wiemer** [comment]
Closing as "not planned" is OK by me, but maybe we add it to the style guide? It really feels do-able but I understand it's low ROI for now

**Comment by appgurueu** [comment]
Personally I don't think this is important and I don't think we should start using "txt" as a language name. If you really just want a block of verbatim text, a code block is the right tool.

If anything the style guide should just remind writers to specify a language for their code blocks, *if applicable*. It may be worth discussing whether e.g. the Lua-like pseudocode used to show the structure of many definitions should be highlighted as Lua (since it is not syntactically valid Lua).

**Comment by wsor4035** [comment]
there is https://gohugo.io/render-hooks/code-blocks/ but i kinda of leaned away from it since you have to completely replace the rendering method, rather than wrap. update liability and all that just for this

**Comment by mark-wiemer** [comment]
Sure. I haven't been keeping up, do we have a style guide we can edit, at least, to close this issue as completed instead of "not planned"?

**Comment by wsor4035** [comment]
> Sure. I haven't been keeping up, do we have a style guide we can edit, at least, to close this issue as completed instead of "not planned"?

stick it on https://dev.luanti.org/about-this-site/guidelines/
