### ISSUE TITLE
Disable Hugo's native HTML warning

### ISSUE THREAD

**Issue by mark-wiemer** [minetest/dev.luanti.org#96]
We should ensure we know what we're doing, then we can probably remove this warning as it's built for untrusted content. Ref #15 and #95

**Comment by wsor4035** [comment]
unless we need to do this, i think its good to leave on? catches cases where we missed escaping something for example

**Comment by mark-wiemer** [comment]
Happy to leave it on by default, but we should look at how to disable it for certain sections of code, there are times when we probably want native HTML like the `<caption>` tag for images. I know Hugo shortcodes exist for that, but there may be a similar example where a Hugo shortcode isn't needed

**Comment by wsor4035** [comment]
your better off using the render image hook in that case, and re using title or alt for a caption https://gohugo.io/render-hooks/images/

**Comment by mark-wiemer** [comment]
@wsor4035 was this completed? If so, can you link the commit/PR? Otherwise can we mark it as not planned for historical purposes?

**Comment by mark-wiemer** [comment]
Pinging to ask to re-open, I didn't see that this was closed as not planned. Hoping we can allow native HTML for comments, for example, there are plenty of cases where it's good. I'm not sure where it's exactly bad, honestly--I know missing escaping things is an idea, but I'm not sure how that might happen in practice.

Current issue is with disabling the spell-checker, ref #83 and #136

**Comment by mark-wiemer** [comment]
Ah, looks like a lot of this convo was in chat, not on GitHub. short answer is that the team was worried our overall use of `<` and `>` in MediaWiki would accidentally create bad native HTML. I disagree, but not a big deal for me. Folks are welcome to re-introduce conversations here or in #luanti-docs if they feel strongly.

For now, our Hugo comments follow this syntax:

```
{{% comment %}} Hello world {{% /comment %}}
```
